// Overly complex
export const complexLog = (message) => {
  const date = new Date();
  const time = `${date.getHours()}:${date.getMinutes()}:${date.getSeconds()}`;
  console.log(`[${date.toDateString()} ${time}] - INFO: ${message}`);
  console.log(
    `Detailed log: This log was generated by the logging system at ${time} on ${date.toDateString()}`
  );
  console.log(
    `Additional info: The log source is 'src/index.js' and log level is 'info'`
  );
};
